### PR TITLE
Add detail on how HTTPS works

### PR DESCRIPTION
**Pull request by TD2106**
Add a more detailed answer on how HTTPS works

### CODE REVIEW

**Comment by tamhoang1412** [comment]
@TD2106 Thank you for your PR. About your modification:
- It is the answer to another question. You should move it [here](https://github.com/tamhoang1412/backend-swe-interview-questions/blob/main/answers/security.md#ssltls).
- The step of the TSL handshake depends a lot on key exchange algorithm. The above process uses RSA key exchange algorithm. One of the other worth considering algorithms is ephemeral Diffie-Hellman. You can find out more [here](https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/). There are also some very interesting videos of Computerphile about those kinds of stuff, the last one points out a disadvantage when using RSA key exchange algorithm compared to ephemeral Diffie-Hellman.
	- [Public Key Cryptography - Computerphile](https://youtu.be/GSIDS_lvRv4)
	- [Secret Key Exchange (Diffie-Hellman) - Computerphile](https://youtu.be/NmM9HA2MQGI)
	- [Key Exchange Problems - Computerphile](https://youtu.be/vsXMMT2CqqE)
- It would be better if you can rephrase the answer in your own words, it will help you remember these things much much longer.

**Comment by tamhoang1412** [comment]
@TD2106 Thank you for your PR. About your modification:
- It is the answer to another question. You should move it [here](https://github.com/tamhoang1412/backend-swe-interview-questions/blob/main/answers/security.md#ssltls).
- The step of the TSL handshake depends a lot on key exchange algorithm. The above process uses RSA key exchange algorithm. One of the other worth considering algorithms is ephemeral Diffie-Hellman. You can find out more [here](https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/). There are also some very interesting videos of Computerphile about those kinds of stuff, the last one points out a disadvantage when using RSA key exchange algorithm compared to ephemeral Diffie-Hellman.
	- [Public Key Cryptography - Computerphile](https://youtu.be/GSIDS_lvRv4)
	- [Secret Key Exchange (Diffie-Hellman) - Computerphile](https://youtu.be/NmM9HA2MQGI)
	- [Key Exchange Problems - Computerphile](https://youtu.be/vsXMMT2CqqE)
- It would be better if you can rephrase the answer in your own words, it will help you remember these things much much longer.

**Comment by TD2106** [comment]
Hi @tamhoang1412 I have just updated the PR, would you mind taking a look ?

**Comment by tamhoang1412** [comment]
@TD2106 Thanks for your update. I find the answer is pretty good now. There are some typo and grammar mistakes that I already fixed, hope you don't mind, and also a few minor changes were added. Please review the answer to see if you wanna change anything before I merge this PR.

**Comment by TD2106** [comment]
Hi @tamhoang1412  I find it all good now. Thanks for fixing the typos and grammar 👍

**Review by tamhoang1412 — APPROVED** [review]

**Comment by nvh95** [comment]
@all-contributors please add @TD2106 for content

**Pull request merged**
